# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

[character] # 編集するモジュールの名前は"character"
success_symbol = "ζ*’ヮ’\\)ζ＜ (bold green)" # "success_symbol"を記号"ζ*'ヮ')ζ＜"で"bold green"(太字の緑色)にセット
